feat: set target-type for ALBs to ip
getoutreach/jsonnet-libs pull request #266
Opened 2024-01-17 19:32 UTC by kaldorn

On the tin.

Adds the following annotation:
```
        'alb.ingress.kubernetes.io/target-type': 'ip',
```

Any other changes are from `jsonnetfmt` running.

2024-01-18 08:52 UTC, dvagapov approved these changes

2024-01-18 08:54 UTC, dvagapov commented
From https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type -> 
```
network plugin must use secondary IP addresses on [ENI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html) for pod IP to use ip mode. e.g.
[amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s)

ip mode is required for sticky sessions to work with Application Load Balancers.
```

2024-02-08 10:30 UTC, zdenekvicar requested changes

2024-02-08 10:30 UTC, zdenekvicar commented on kubernetes/outreach.libsonnet
> +        'alb.ingress.kubernetes.io/target-type': 'ip',
Hello @kaldorn , based on previous incident caused by changes in jsonnet-libs [ICM-676](https://outreach-io.atlassian.net/browse/ICM-676), I need to ask for a condition to ensure this is not spreading everywhere without a control. One of the learnings in the incident was that we need to ensure changes are deployed on staging where we need a chance to see how this works and whether it affects anything. Could you please add such condition ? 

Also, I am missing some context in the PR. Why are we doing this change ? What is the benefit of doing this, and is there any downside of this ? Is this part of any bigger project (like the CrossAZ networking which @jan-ludvik is leading) ?

I am blocking the PR until we have those questions answered and staging condition in place.

2024-02-08 17:31 UTC, zdenekvicar commented on kubernetes/outreach.libsonnet
> +        'alb.ingress.kubernetes.io/target-type': 'ip',
discussion moved to slack 👉 https://outreach-hq.slack.com/archives/C06HLD1DARH/p1707388405057919

2024-02-09 08:23 UTC, jan-ludvik approved these changes
Will be deployed only to staging. Awesome, thanks!

2024-02-09 10:33 UTC, zdenekvicar approved these changes
All my questions / concerns were explained and/or addressed in slack thread: https://outreach-hq.slack.com/archives/C06HLD1DARH/p1707388405057919

LGTM, thank you

2024-02-12 08:23 UTC, merged